Feature/8
Jahongir1507/BlogPost pull request #1
Opened 2022-09-28 13:36 UTC by Jahongir1507

2022-09-28 16:32 UTC, Jahongir1507 commented
ba'zi bir kamchiliklar tufayli tug'irlangandan keyin qayta ochiladi

2022-09-29 07:16 UTC, Jahongir1507 commented
deficiencies have been eliminated

2022-09-29 10:38 UTC, napster1991 requested changes

2022-09-29 10:38 UTC, napster1991 commented on WeebApp/Areas/user/Controllers/CreatorController.cs
> +    public class CreatorController : Controller
Controller nomini PostControllerga rename qilin.
/User/Views papkada ham Creator papkani Postga rename qilish esdan chiqmasin. sababini chunmasez, bolladan so'ren

2022-09-29 10:38 UTC, napster1991 commented on WeebApp/Areas/user/Views/Creator/Index.cshtml
> +@System.Globalization.CultureInfo.CurrentUICulture
bu qator kod nega kerak?

2022-09-29 10:38 UTC, napster1991 commented on WeebApp/Controllers/PostsController.cs
> +        public async Task<IActionResult> MyPosts()
bu methodni keragi yo'q. tepada Index bor-ku huddi shunaqa

2022-09-29 10:38 UTC, napster1991 commented on WeebApp/Areas/user/Controllers/CreatorController.cs
> +        [Authorize]
[Authorize] keremas. sababini chunmasez, so'ren

2022-09-29 10:38 UTC, napster1991 commented on WeebApp/Controllers/PostsController.cs
>          public async Task<IActionResult> Index()
Index() va Details() (sizdigi View(). shuni Detailsga rename qilin) methodlardan boshqalarini o'chirib tashen. bu controllerni ichida ula keremas. sababini chunmasez, so'ren

2022-09-29 10:38 UTC, napster1991 commented on WeebApp/Models/AddPostViewModel.cs
>          public DateTime CreatedDate { get; set; } = DateTime.Now;
7-8 qatordigi kod keremas. sababini so'ren

2022-09-29 10:38 UTC, napster1991 commented on WeebApp/Models/Domain/Post.cs
> +        public string? CreatorId { get; set; }
"string?" emas, balki "string" bo'lishi kerak. sababini chunmasez, so'ren

2022-09-29 10:38 UTC, napster1991 commented on WeebApp/Models/UpdatePostViewModel.cs
>          public Guid Id { get; set; }
UpdatePostViewModel qanaqa bo'lishi kerakligini Dilshoddan so'ren

2022-09-29 10:38 UTC, napster1991 commented on WeebApp/Views/Posts/Add.cshtml
>  <h1>Add Post</h1>
/Views/Posts papkani ichidigi Indexdan tashqari qogan hamma fayllarni delete qilish kerak

2022-10-04 06:06 UTC, Jahongir1507 commented on WeebApp/Models/Domain/Post.cs
> +        public string? CreatorId { get; set; }
bu muommo ham hal boldi

2022-10-04 06:06 UTC, Jahongir1507 commented on WeebApp/Models/UpdatePostViewModel.cs
>          public Guid Id { get; set; }
ha tushundim

2022-10-04 06:08 UTC, Jahongir1507 commented on WeebApp/Views/Posts/Add.cshtml
>  <h1>Add Post</h1>
uniyam tug'irlab ixchamroq holga keltirib quydim

2022-10-04 06:09 UTC, merged

2022-10-04 06:13 UTC, napster1991 requested changes

2022-10-04 06:13 UTC, napster1991 commented on WeebApp/Areas/user/Controllers/PostController.cs
> +            var UserPost = _context.Posts.OrderByDescending(p => p.CreatedDate).Take(8);
37-39 qatorlar nega kerak? oldingisi to'g'ri edi-ku!

2022-10-04 06:13 UTC, napster1991 commented on WeebApp/Areas/user/Controllers/PostController.cs
>          public async Task<IActionResult> Create(AddPostViewModel addPostRequest)
bu methodni oldni holatini qaytarib, ana o'shanga AddPostViewModel'ni qo'llash kerak. Dilshod bilan maslahatlashin

2022-10-04 06:13 UTC, napster1991 commented on WeebApp/Areas/user/Controllers/PostController.cs
> +          //  ViewData["CreatorId"] = new SelectList(_context.Users, "Id", "Id", post.CreatorId);
bu qatorni remove qivorin

2022-10-04 06:13 UTC, napster1991 commented on WeebApp/Areas/user/Controllers/PostController.cs
> +        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Text,CreatedDate,CreatorId")] UpdatePostViewModel post)
bu methodni test qilish kerak

2022-10-04 06:13 UTC, napster1991 commented on WeebApp/Controllers/HomeController.cs
> +
bu bo'shliqlar bo'lishi kerak emas